In [15]:
import numpy as np
z= np.zeros((4,5))
z
type(z)
z.shape

b = [[1,4,7],[13, 11, 9],[1,-8, 17]]
A = np.matrix()
print(A.shape)
print(np.linalg.matrix_rank(A))
print(np.linalg.inv(A))
print(np.linalg.inv(A)*A)

(3, 3)
3
[[-0.18579627  0.08895265  0.02941176]
 [ 0.15208034 -0.0071736  -0.05882353]
 [ 0.08249641 -0.00860832  0.02941176]]
[[ 1.00000000e+00 -1.66533454e-16 -2.28983499e-16]
 [-1.38777878e-17  1.00000000e+00 -9.71445147e-17]
 [-6.93889390e-18  0.00000000e+00  1.00000000e+00]]


### Types of Matrices
https://en.wikipedia.org/wiki/List_of_matrices